version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: daily
    groups:
      prod:
        dependency-type: production
      dev:
        dependency-type: development
