defmodule Trogon.Dispatcher.Context do
  @moduledoc """
  The value threaded through every middleware and handed to the handler.

  `message` is the struct being dispatched, matched by the dispatch clause that built this context; no function on
  this module replaces it. `kind` is `:command` or `:query`, from the registration. `dispatcher` is the module whose
  `dispatch_message/2` was called; `registered_by` is the dispatcher that declared the registration, the message's
  owning boundary.

  Reserved concepts (`message_id`, `correlation_id`, `causation_id`, `actor`) are first-class typed fields rather
  than entries in `private`, because host apps need to read them. `assigns` is host-app space and the library never
  reads it. `private` is middleware scratch space and should be namespaced by the owning module.

  `message_id` identifies the message in this context. `causation_id` names the `message_id` of whatever message
  caused it. Neither is generated by the library: a caller sets them, or leaves both `nil`.

  The context is the only value a middleware sees. It travels forward into the pipeline and back out again, so a
  middleware reads and writes it on both legs and never touches the message or the response as separate arguments.

  `response` is empty on the way in and holds the handler's answer on the way out. A middleware halts by putting a
  response without calling `next`.
  """

  alias Trogon.Dispatcher.DispatchOptions

  @enforce_keys [:message, :kind, :dispatcher, :registered_by]
  defstruct [
    :message,
    :kind,
    :dispatcher,
    :registered_by,
    message_id: nil,
    correlation_id: nil,
    causation_id: nil,
    actor: nil,
    assigns: %{},
    private: %{},
    response: nil
  ]

  @type kind :: :command | :query

  @type t :: %__MODULE__{
          message: struct(),
          kind: kind(),
          dispatcher: module() | nil,
          registered_by: module() | nil,
          message_id: term() | nil,
          correlation_id: term() | nil,
          causation_id: term() | nil,
          actor: term() | nil,
          assigns: map(),
          private: map(),
          response: response() | nil
        }

  @type response :: :ok | {:ok, struct()} | {:error, term()}

  @doc """
  Builds a context from a message and caller options.

  Dispatchers build the struct inline at compile time; this is the runtime equivalent, used by test helpers and by
  anything that needs a context without going through a dispatcher.

  `overrides` accepts `:kind`, `:dispatcher` and `:registered_by`.
  """
  @spec new(struct(), DispatchOptions.t(), keyword()) :: t()
  def new(message, options \\ DispatchOptions.new!(), overrides \\ []) when is_struct(message) do
    options = DispatchOptions.validate!(options)
    dispatcher = Keyword.get(overrides, :dispatcher)

    %__MODULE__{
      message: message,
      kind: Keyword.get(overrides, :kind, :command),
      dispatcher: dispatcher,
      registered_by: Keyword.get(overrides, :registered_by, dispatcher),
      message_id: options.message_id,
      correlation_id: options.correlation_id,
      causation_id: options.causation_id,
      actor: options.actor,
      assigns: options.assigns,
      private: Keyword.get(overrides, :private, %{})
    }
  end

  @doc """
  Assigns a value into host-app space.
  """
  @spec assign(t(), atom(), term()) :: t()
  def assign(%__MODULE__{} = context, key, value) when is_atom(key) do
    %{context | assigns: Map.put(context.assigns, key, value)}
  end

  @doc """
  Puts a value into middleware scratch space under the owning module's key.
  """
  @spec put_private(t(), module(), term()) :: t()
  def put_private(%__MODULE__{} = context, owner, value) when is_atom(owner) do
    %{context | private: Map.put(context.private, owner, value)}
  end

  @doc """
  Puts the response the pipeline carries back out.

  A middleware that calls `next` receives a context that already carries a response. One that halts sets its own.

  ## Example

      def call(context, next, _options) do
        if allowed?(context) do
          next.(context)
        else
          Context.put_response(context, {:error, :unauthorized})
        end
      end
  """
  @spec put_response(t(), response()) :: t()
  def put_response(%__MODULE__{} = context, response) do
    %{context | response: response}
  end

  @doc """
  Reads a value out of middleware scratch space.
  """
  @spec get_private(t(), module(), term()) :: term()
  def get_private(%__MODULE__{} = context, owner, default \\ nil) when is_atom(owner) do
    Map.get(context.private, owner, default)
  end

  @doc """
  Builds options for a nested dispatch out of the context of the dispatch currently in flight.

  Carries `correlation_id`, `actor` and `assigns` forward, and sets `causation_id` to the current context's `message_id`: the
  message in flight is what causes the nested dispatch. It does not carry `message_id` itself forward, since the
  nested dispatch has an identity of its own; set it yourself if the nested message carries one.

  ## Example

      def handle_message(%ArchiveUser{} = message, context) do
        options = Context.to_dispatch_options(context)
        MyApp.Dispatcher.dispatch_message(%NotifyUser{user_id: message.user_id}, options)
      end
  """
  @spec to_dispatch_options(t()) :: DispatchOptions.t()
  def to_dispatch_options(%__MODULE__{} = context) do
    DispatchOptions.new!(
      correlation_id: context.correlation_id,
      causation_id: context.message_id,
      actor: context.actor,
      assigns: context.assigns
    )
  end
end
