defmodule Trogon.Dispatcher.DispatchOptions do
  @moduledoc """
  Caller-supplied options for a dispatch.

  Everything a caller is allowed to seed the `Trogon.Dispatcher.Context` with lives here. `private` is deliberately
  absent: it is middleware scratch space, not caller input.

  `message_id` identifies the message being dispatched. `causation_id` names the `message_id` of whatever message
  caused it. Neither is generated by the library: a caller sets them, or leaves both `nil`.

  The type is opaque. Build it with `new/1` or `new!/1`, which hold the invariants, and read it through the accessor
  functions. A struct literal skips `new/1`, so a dispatch checks the same invariants again before it builds a context
  and raises `Trogon.Dispatcher.InvalidDispatchOptionsError` when they do not hold.
  """

  alias Trogon.Dispatcher.InvalidDispatchOptionsError

  defstruct message_id: nil,
            correlation_id: nil,
            causation_id: nil,
            actor: nil,
            assigns: %{}

  @opaque t :: %__MODULE__{
            message_id: term() | nil,
            correlation_id: term() | nil,
            causation_id: term() | nil,
            actor: term() | nil,
            assigns: %{optional(atom()) => term()}
          }

  @type option ::
          {:message_id, term() | nil}
          | {:correlation_id, term() | nil}
          | {:causation_id, term() | nil}
          | {:actor, term() | nil}
          | {:assigns, %{optional(atom()) => term()}}

  @keys [:message_id, :correlation_id, :causation_id, :actor, :assigns]

  @doc """
  Builds options, returning an error when they break an invariant.

  ## Example

      {:ok, options} = DispatchOptions.new(actor: actor, assigns: %{request_id: "req-1"})
  """
  @spec new([option()]) :: {:ok, t()} | {:error, InvalidDispatchOptionsError.t()}
  def new(opts \\ []) do
    with :ok <- validate_keyword(opts),
         :ok <- validate_keys(opts) do
      __MODULE__ |> struct(opts) |> validate()
    end
  end

  @doc """
  Builds options, raising `Trogon.Dispatcher.InvalidDispatchOptionsError` when they break an invariant.
  """
  @spec new!([option()]) :: t()
  def new!(opts \\ []) do
    case new(opts) do
      {:ok, options} -> options
      {:error, error} -> raise error
    end
  end

  @doc false
  @spec validate!(term()) :: t()
  def validate!(%__MODULE__{} = options) do
    case validate(options) do
      {:ok, options} -> options
      {:error, error} -> raise error
    end
  end

  def validate!(options) do
    raise ArgumentError, "expected a %#{inspect(__MODULE__)}{} as the second argument, got: #{inspect(options)}"
  end

  @spec message_id(t()) :: term() | nil
  def message_id(%__MODULE__{message_id: message_id}), do: message_id

  @spec correlation_id(t()) :: term() | nil
  def correlation_id(%__MODULE__{correlation_id: correlation_id}), do: correlation_id

  @spec causation_id(t()) :: term() | nil
  def causation_id(%__MODULE__{causation_id: causation_id}), do: causation_id

  @spec actor(t()) :: term() | nil
  def actor(%__MODULE__{actor: actor}), do: actor

  @spec assigns(t()) :: %{optional(atom()) => term()}
  def assigns(%__MODULE__{assigns: assigns}), do: assigns

  defp validate(%__MODULE__{assigns: assigns} = options) do
    cond do
      not is_map(assigns) ->
        {:error, InvalidDispatchOptionsError.exception(field: :assigns, value: assigns, reason: :not_a_map)}

      not Enum.all?(Map.keys(assigns), &is_atom/1) ->
        {:error, InvalidDispatchOptionsError.exception(field: :assigns, value: assigns, reason: :non_atom_key)}

      true ->
        {:ok, options}
    end
  end

  defp validate_keyword(opts) do
    if Keyword.keyword?(opts) do
      :ok
    else
      {:error, InvalidDispatchOptionsError.exception(field: nil, value: opts, reason: :not_a_keyword)}
    end
  end

  defp validate_keys(opts) do
    case Keyword.keys(opts) -- @keys do
      [] ->
        :ok

      [key | _rest] ->
        {:error, InvalidDispatchOptionsError.exception(field: key, value: opts[key], reason: :unknown_key)}
    end
  end
end
