defmodule Trogon.Dispatcher.DispatchOptions do
  @moduledoc """
  Caller-supplied options for a dispatch.

  Everything a caller is allowed to seed the `Trogon.Dispatcher.Context` with lives here. `private` is deliberately
  absent: it is middleware scratch space, not caller input.

  `message_id` identifies the message being dispatched. `causation_id` names the `message_id` of whatever message
  caused it. Neither is generated by the library: a caller sets them, or leaves both `nil`.
  """

  defstruct message_id: nil,
            correlation_id: nil,
            causation_id: nil,
            actor: nil,
            assigns: %{}

  @type t :: %__MODULE__{
          message_id: term() | nil,
          correlation_id: term() | nil,
          causation_id: term() | nil,
          actor: term() | nil,
          assigns: map()
        }
end
