defmodule Trogon.Dispatcher.DispatchOptions do
  @moduledoc """
  Caller-supplied options for a dispatch.

  Everything a caller is allowed to seed the `Trogon.Dispatcher.Context` with lives here. `private` is deliberately
  absent: it is middleware scratch space, not caller input.

  `message_id` identifies the message being dispatched. `causation_id` names the `message_id` of whatever message
  caused it. Neither is generated by the library: a caller sets them, or leaves both `nil`.

  `assigns` is a map with atom keys. Types are not checked at runtime: `t:option/0` and `t:t/0` state them, and
  `Trogon.Credo.Plugin.Dispatcher` reports a literal that breaks them. `new/1` and `new!/1` reject unknown keys.

  Build it with `new/1` or `new!/1`. Everything downstream trusts options it receives, so a struct literal that skips
  them is a bug at the call site.
  """

  alias Trogon.Dispatcher.InvalidDispatchOptionsError

  defstruct message_id: nil,
            correlation_id: nil,
            causation_id: nil,
            actor: nil,
            assigns: %{}

  @type t :: %__MODULE__{
          message_id: term() | nil,
          correlation_id: term() | nil,
          causation_id: term() | nil,
          actor: term() | nil,
          assigns: %{optional(atom()) => term()}
        }

  @type option ::
          {:message_id, term() | nil}
          | {:correlation_id, term() | nil}
          | {:causation_id, term() | nil}
          | {:actor, term() | nil}
          | {:assigns, %{optional(atom()) => term()}}

  @keys [:message_id, :correlation_id, :causation_id, :actor, :assigns]

  @doc """
  Builds options, returning an error for an unknown key.

  ## Example

      {:ok, options} = DispatchOptions.new(actor: actor, assigns: %{request_id: "req-1"})
  """
  @spec new([option()]) :: {:ok, t()} | {:error, InvalidDispatchOptionsError.t()}
  def new(opts \\ []) do
    with :ok <- validate_keys(opts) do
      {:ok,
       %__MODULE__{
         message_id: Keyword.get(opts, :message_id),
         correlation_id: Keyword.get(opts, :correlation_id),
         causation_id: Keyword.get(opts, :causation_id),
         actor: Keyword.get(opts, :actor),
         assigns: Keyword.get(opts, :assigns, %{})
       }}
    end
  end

  @doc """
  Builds options, raising `Trogon.Dispatcher.InvalidDispatchOptionsError` for an unknown key.
  """
  @spec new!([option()]) :: t()
  def new!(opts \\ []) do
    case new(opts) do
      {:ok, options} -> options
      {:error, error} -> raise error
    end
  end

  defp validate_keys(opts) do
    case Enum.reject(Keyword.keys(opts), &(&1 in @keys)) do
      [] ->
        :ok

      [key | _rest] ->
        {:error, InvalidDispatchOptionsError.exception(field: key, value: opts[key], validation: :unknown_key)}
    end
  end
end
