name: cd

on:
  release:
    types:
      - released
      - prereleased
  workflow_dispatch:
    inputs:
      ref-name:
        description: Release tag to publish, in the format "[package name]@v[version]"
        required: true
        type: string

jobs:
  publish:
    name: Publish to Hex.pm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: 1password/load-secrets-action@e544b780808654ba8ceba5fb2fe2897103d92ff4 # v4
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          HEX_API_KEY: "${{ secrets.SECRETS_VAULT }}/HEX_API_KEY"
      - uses: straw-hat-team/github-actions-workflows/elixir/umbrella-publish@5ab906d801d41b723636b498e57509e18db1856a # v1.9.1
        with:
          hex-api-key: ${{ env.HEX_API_KEY }}
          ref-name: ${{ github.event_name == 'workflow_dispatch' && inputs.ref-name || github.ref_name }}
