name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  qa:
    uses: straw-hat-team/github-actions-workflows/.github/workflows/elixir-quality-assurance.yml@f93d234b888e3929141c5faed223e6071fe2c60e # v1.9.0
    with:
      mix-in-umbrella-deps: true
