name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  qa:
    uses: straw-hat-team/github-actions-workflows/.github/workflows/elixir-quality-assurance.yml@a47798ffe54ef6079d7a1212ea93058cb8d0d4d9 # master
