name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  qa:
    uses: straw-hat-team/github-actions-workflows/.github/workflows/elixir-quality-assurance.yml@9d9de721069136b981894947c85a0c27ab14a392 # master
