name: hex-publish-docs

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: Package to publish docs for
        required: true
        type: choice
        options:
          - trogon_commanded
          - trogon_error
          - trogon_proto
          - trogon_result
          - trogon_typeprovider

jobs:
  publish-docs:
    name: Publish Docs to Hex.pm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: 1password/load-secrets-action@92467eb28f72e8255933372f1e0707c567ce2259 # v4
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          HEX_API_KEY: "${{ secrets.SECRETS_VAULT }}/HEX_API_KEY"
      - uses: straw-hat-team/github-actions-workflows/elixir/publish-docs@a47798ffe54ef6079d7a1212ea93058cb8d0d4d9 # master
        with:
          hex-api-key: ${{ env.HEX_API_KEY }}
          package-name: ${{ inputs.package-name }}
