name: hex-publish-docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish-docs:
    name: Publish Docs to Hex.pm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-name:
          - one_piece_graceful_shutdown
          - trogon_commanded
          - trogon_error
          - trogon_proto
          - trogon_result
          - trogon_typeprovider
    steps:
      - uses: actions/checkout@v6
      - uses: 1password/load-secrets-action@v4
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          HEX_API_KEY: "${{ secrets.SECRETS_VAULT }}/HEX_API_KEY"
      - uses: straw-hat-team/github-actions-workflows/elixir/publish-docs@master
        with:
          hex-api-key: ${{ env.HEX_API_KEY }}
          package-name: ${{ matrix.package-name }}
